name: Frontend Tests
on:
  push:
    branches: [ main, frontend_tests ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, frontend_tests ]
    paths:
      - 'frontend/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        npx playwright install --with-deps

    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start backend server
      run: |
        cd backend
        python3 -m app.main &     # Start in background
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        FEDERAL_TAX_URL: https://www.irs.gov/filing/federal-income-tax-rates-and-brackets
        CAPITAL_GAINS_TAX_URL: https://www.irs.gov/taxtopics/tc409
        STANDARD_DEDUCTION_URL: https://www.irs.gov/publications/p17
        RMD_TABLE_URL: https://www.irs.gov/publications/p590b
        SERVER_ADDR: 127.0.0.1
        SERVER_HOSTNAME: localhost
        SERVER_PORT: 8000
        FRONTEND_ADDR: 127.0.0.1
        FRONTEND_HOSTNAME: localhost
        FRONTEND_POR: 5173

    - name: Run Playwright tests
      run: |
        cd frontend
        npx playwright test
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
